---
title: Events
---

erDiagram
    events ||--|{ seeds : ""
    events }o--|| storms : ""
    events }o--|| fishnet_points : ""
    structures }o--o{ events : ""
    models }|--o{ events : ""
    runs }o--|| models : ""
    runs }o--|| events : ""
    storms ||--o{ grids : ""
    events ||--o{ grids : ""


    storms {
        storm_id int PK
        storm_rank int
        storm_type str
        datetime datetime
        duration_hrs int
        centroid geom
        mean_precip float
    }
    fishnet_points {
        fishnet_point_id int PK
        weight float
        geom geom
    }
    events {
        event_id int PK
        storm_id int FK
        fishnet_point_id int FK
        event_type enum
        block_id int
        realization_id int
    }
    seeds {
        seed_id int PK
        event_id int FK
        process_id int
        realization_seed int
        block_seed int
        event_seed int
    }
    structures {
    }
    events {
    }
    runs {
    }
    grids {
    }