---
title: Models
---

erDiagram

    observations }o--|| gages : ""
    models ||--o{ model_elements : ""
    gages |o--o{ model_elements : ""

    structures ||--|{ model_elements : ""
    events ||--o{ structures : ""
    run_catalog }o--|| models : ""
    run_catalog }o--|| events : ""
    models ||--o{ model_linkages : "donor"
    models ||--o{ model_linkages : "receiver"
    hotfixes }o--|| models : ""

    models {
        model_id int PK
        model_type str
        model_name str
        model_version str
        geom geom
        stac_metadata uri
    }
    model_elements {
        element_id int PK
        model_id int FK
        structure_id int
        structure_type str
        gage_id str FK
        element str
        geom geom
    }

    model_linkages {
        linkage_id int PK
        donor_model_id int FK
        donor_model_type str
        donor_site_type str
        donor_site_id str FK
        receiver_model_id int FK
        receiver_model_type str
        receiver_site_type str
        receiver_site_id str FK
    }

    hotfixes {
        model_id int FK
        model_version str
        hotfix_id int PK
        issue_description str
        status enum
        resolved_at datetime
    }