---
title: Models
---

erDiagram

    obs_ts }o--|| gages : ""
    models ||--o{ model_elements : ""
    model_elements ||--o{ output_ts : ""
    gages |o--o{ model_elements : ""
    runs ||--o{ output_ts : ""
    events ||--o{ output_grids : ""
    structures ||--|{ model_elements : ""
    structures ||--o{ structure_failure_elev : ""
    events ||--o{ structure_failure_elev : ""
    runs }o--|| models : ""
    runs }o--|| events : ""
    models ||--o{ model_linkages : "donor"
    models ||--o{ model_linkages : "receiver"

    events {
       }
    gages {
        gage_id str PK
        gage_name str
        gage_owner str
        ams array
        geom geom
    }
    models {
        model_id int PK
        model_type str
        model_name str
        model_version str
        geom geom
        metadata uri
    }
    model_elements {
        element_id int PK
        model_id int FK
        structure_id int
        structure_type str
        gage_id str FK
        element str
        geom geom
    }
    output_ts {
        run_id int FK
        element_id int FK
        timestamp datetime
        variable str
        value float
        units str
    }
    obs_ts {
        gage_id str FK
        timestamp datetime
        variable str
        value float
        units str
    }
    model_linkages {
        linkage_id int PK
        donor_model_id int FK
        donor_model_type str
        donor_site_type str
        donor_site_id str FK
        receiver_model_id int FK
        receiver_model_type str
        receiver_site_type str
        receiver_site_id str FK
    }
    structures {
    }
    runs {
        run_id int PK
        event_id int FK
        model_id int FK
        run_type enum
        timestamp datetime
        success bool
        metadata uri
    }
    structure_failure_elev {
        structure_response_id int FK
        event_id int FK
        failure_elev float
    }