---
title: Structures
---

erDiagram

    models ||--o{ model_elements : ""
    events ||--o{ output_ts : ""
    levees ||--o{ structure_response :""
    levees ||--|{ model_elements : ""
    dams ||--o{ structure_response : ""
    dams ||--|{ model_elements : ""
    buildings ||--o{ model_elements : ""
    model_elements ||--o{ output_ts : ""
    events ||--o{ structure_failure_elev : ""
    structure_failure_elev ||--o{ structure_response : ""

    events {
    }
    models{
    }
    model_elements {
    }

    levees {
        structure_id int PK
        model_id int FK
        system_type str
        name str
        nld_name str
        nld_segment_id str
        top_elev float
        toe_elev float
        source str
        geom geom
    }
    dams {
        structure_id int PK
        model_id int FK
        system_type str
        name str
        nid_name str
        source str
        geom geom
    }
    structure_response {
        structure_response_id int PK
        structure_id int FK
        failure_mode str
        source str
        prob_x float
        prob_y float
    }
    structure_failure_elev {
        structure_response_id int PK
        event_id int FK
        failure_elev float
    }

    buildings {
        structure_id int PK
        source_building_id str
        inventory_source str
        inventory_version str
        latitude float
        longitude float
        geom geom
        state_fips str
        county_fips str
        census_block_fips str
        occupancy_type str
        general_building_type str
        number_stories int
        area_sqft float
        foundation_type str
        first_floor_height_ft float
        basement_type int
        building_cost float
        content_cost float
        inventory_cost float
        bldg_insurance_deductible float
        bldg_insurance_limit float
        content_insurance_deductible float
        content_insurance_limit float
        ground_elevation_ft float
        pop_2am int
        pop_2pm int
        pop_2am_under65 int
        pop_2am_over65 int
        pop_2pm_under65 int
        pop_2pm_over65 int
        source str
    }
